# Generated by Django 5.2.1 on 2025-06-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rr', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='checklist',
            index=models.Index(fields=['user', 'created_at'], name='rr_checklis_user_id_f9470d_idx'),
        ),
    ]
