# Generated by Django 5.2.1 on 2025-06-11 02:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rr', '0002_checklist_rr_checklis_user_id_f9470d_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='score',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=1)]),
        ),
    ]
